name: Playwright Google Sign-In Test

on:
  push:
    branches:
      - feat/testing
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      GOOGLE_SIGNIN_EMAIL: ${{ secrets.GOOGLE_SIGNIN_EMAIL }}
      GOOGLE_SIGNIN_PASSWORD: ${{ secrets.GOOGLE_SIGNIN_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright Test
        run: npx playwright test tests/e2e/
